package.json
src/dataHandler.js

@jourdain Here's what I think should work, but I don't know how to test it...

Use itk browser interface

---

package.json

Suggested-by: Sebastien Jourdain <sebastien.jourdain@kitware.com>

build(package): use shx for copying files on Windows

---

package-lock.json
package.json

Now includes support for 19 different file formats.

feat(itk): Bump itk to 5.0.0

---

dist/index.html
dist/manifest.json

Generated from https://tomitm.github.io/appmanifest/

feat(progressive): Add Web App Manifest

---

src/viewer.js

Transfer function widget

---

package-lock.json
package.json
src/fetchBinaryContent.js
webpack.config.js

This also fixes the fetchBinaryContent functionality

chore(deps): Bump vtk.js to 5.5.0

---

package-lock.json
package.json
src/index.js
src/processFiles.js
src/userInterface.js

When more than one file is selected, it is assumed to be a DICOM series and read with
itkreadImageDICOMFileSeries.
BREAKING CHANGE: processFile is now processFiles and it accepts an Array of File's or FileList.

feat(processFiles): Add DICOM series support

---

dist/index.html
package-lock.json
package.json

@jourdain This makes local development easier and less confusing by not installing the service worker.

Local development

---

dist/index.html
src/ItkVtkImageViewer.mcss
src/createViewer.js
src/index.js
src/processFiles.js
src/proxyManagerConfiguration.js
src/userInterface.js

Refactor to use the 3D viewer to use the ProxyView.
Next steps are to create the 2D view states.

Proxy view

---

src/ItkVtkViewProxy.js

Suggested-by: Alexis Girault <alexis.girault@kitware.com>

fix(Annotation): Improve probe annotation formatting with a table

---

bin/ItkVtkImageViewer-cli.js
package-lock.json
package.json

fix(Dependencies): Use opn instead of open

---

package-lock.json
package.json
src/proxyManagerConfiguration.js

fix(Dependencies): Bump vtk.js to 7.6.0

---

src/createViewer.js

Fixes opacity and window / level.

fix(Viewer): Re-apply opacity transfer function after setImage

---

src/userInterface/createMainUI.js

Prevent unnecessary update when the widget is enabled or disabled.

fix(cropping): Only set planes whech widget planes changed

---

package-lock.json
src/createViewer.js

The button state is not changed until after the event is handled.

fix(createViewer): Fix view mode changed event listening

---

src/userInterface/ItkVtkViewer.module.css

Co-authored-by: Wesley Banfield <wesleybanfield@gmail.com>

fix(ItkVtkViewer.module.css): Remove extra colon

---

README.md

After migration of matt.mccormick organization to Kitware organization.

doc(README): Update Azure badge

---

src/UserInterface/Geometries/createGeometryColorPresetSelector.js
src/UserInterface/PointSets/createPointSetColorPresetSelector.js

@banesullivan
xref https://github.com/InsightSoftwareConsortium/itk-jupyter-widgets/pull/171

fix(Geometries,PointSet): Use Viridis as default colormap

---

.travis.yml

Also use 'npm ci' instead of 'npm install'.

ci(Travis): Update from trusty to xenial

---

src/UserInterface/Image/createColorRangeInput.js
src/UserInterface/Image/createTransferFunctionWidget.js
src/createViewer.js

feat(ColorRange): Support custom image colormaps

---

package-lock.json
package.json

Re: https://github.com/Kitware/vtk-js/pull/1238
https://github.com/InsightSoftwareConsortium/itkwidgets/issues/216

fix(Dependencies): Bump vtk.js to 11.8.0

---

karma.conf.js
package-lock.json
package.json
src/processFiles.js
webpack.config.js

Currently, adds native support for .vtp, .vtu file. More in the future.

feat(processFiles): Add readPolyDataFile support

---

src/ItkVtkViewProxy.js

fix(ScaleBar): Place text under bar

---

README.md
doc/content/docs/index.md

doc(Citation): Add Zenodo badge

---

src/UserInterface/Geometries/createGeometryOpacitySlider.js
src/UserInterface/PointSets/createPointSetOpacitySlider.js

To address:
https://github.com/InsightSoftwareConsortium/itkwidgets/issues/262

fix(GeometryPointSetOpacity): Set all values when changed

---

src/UserInterface/createGeometriesUI.js
src/UserInterface/createPointSetsUI.js

When available. Also with PointSetUI.

feat(GeometriesUI): Use polyData.metadata.name for displayed name

---

src/UserInterface/Image/createDistanceButton.js
src/UserInterface/ItkVtkViewer.module.css
src/UserInterface/createImageUI.js
src/UserInterface/icons/length-tool.svg
src/ViewerStore.js

Add a ruler tool to the image UI using the vtk-js [distance widget](https://kitware.github.io/vtk-js/api/Interaction_Widgets_DistanceWidget.html)

Add distance/ruler tool to image UI

---

package-lock.json
package.json
src/createViewer.js

Adds initial support for multi-component slice rendering.
Currently requires this [PR](https://github.com/Kitware/vtk-js/pull/1326) in order to try it out.

fix(Viewer): Initial support for per-component lut/pwf

---

package-lock.json
package.json

Option 1 from: https://prettier.io/docs/en/precommit.html

build(pre-commit-hook): Run prettier as a pre-commit Git hook

---

package-lock.json
package.json

Addresses reading multiple files that are not DICOM series, reading
DICOM series.

fix(Dependencies): Bump itk.js to 12.0.1

---

package-lock.json
package.json
src/UserInterface/Image/createGradientOpacitySlider.js
src/UserInterface/Image/createLabelMapColorWidget.js
src/UserInterface/Image/createPlaneIndexSliders.js
src/UserInterface/Image/createSampleDistanceSlider.js
src/UserInterface/Main/createCroppingButtons.js
src/UserInterface/Main/createResetCameraButton.js
src/createViewer.js

More fixes for labelmaps

---

azure-pipelines.yml
karma.conf.js
package-lock.json
package.json
test/createViewerTest.js
test/run.sh

- Improved DICOM support (now based on GDCM).
- Improve IO performance.

feat(IO): Bump itk.js to 12.2.0

---

package-lock.json
package.json
src/Rendering/updateSliceProperties.js
src/UserInterface/Image/createColorRangeInput.js
src/UserInterface/Image/createComponentSelector.js
src/UserInterface/Image/createLabelMapColorWidget.js
src/UserInterface/Main/createInterpolationButton.js
src/ViewerStore.js
src/createViewer.js
src/index.js

Sets `independentComponents = false` under conditions described in #257.

WIP: fix(Viewer): Make sure 2D images are rendered as before

---

src/utils.js

The factory function is useful for constructing vtk.js PolyData objects
from their data.

feat(utils): Export 'vtk'

---

src/UserInterface/Geometries/createGeometryColorChooser.js

Has a good contrast with the viridis colormap used for images.

fix(createGeometryColorChooser): Default geometry color is red

---

package-lock.json
package.json
src/UserInterface/Image/createLabelMapColorWidget.js
src/UserInterface/applyCategoricalColorToLookupTableProxy.js
src/createViewer.js

Improvement for volume rendering of labelmap data, requires this [change](https://github.com/Kitware/vtk-js/pull/1411) from `vtk.js`.
Here's a preview of the change:

fix(LabelMap): Fixes targeting volume rendering of labelmap data

---

src/ItkVtkViewProxy.js
src/createViewer.js
src/fetchJsonContent.js
src/index.js
src/processFiles.js

Supports loading annotations via url parameter `annotations`.  Example annotations file can be found [here](https://thewtex.github.io/allen-ccf-itk-vtk-zarr/allen_ontology_50.json).

fix(LabelMaps): Support loading and displaying annotations

---

package-lock.json
package.json
src/ItkVtkViewProxy.js
src/Rendering/createLabelMapRendering.js
src/Rendering/index.js
src/Rendering/updateLabelMapComponentWeight.js
src/Rendering/updateLabelMapPiecewiseFunction.js
src/Rendering/updateVolumeProperties.js
src/UserInterface/Geometries/createGeometryOpacitySlider.js
src/UserInterface/Image/createLabelMapColorWidget.js
src/UserInterface/Image/createLabelMapWeightWidget.js
src/UserInterface/ItkVtkViewer.module.css
src/ViewerStore.js
src/createViewer.js

Needs this [change](https://github.com/Kitware/vtk-js/pull/1434) from `vtk.js`.

fix(Viewer): Make labelmap component proportional in volume rendering

---

package-lock.json
package.json
src/Rendering/createImageRendering.js
src/Rendering/updateLabelMapComponentWeight.js
src/Rendering/updateLabelMapPiecewiseFunction.js
src/Rendering/updateSliceProperties.js
src/Rendering/updateVolumeProperties.js
src/UserInterface/Image/createComponentSelector.js
src/UserInterface/createImageUI.js
src/ViewerStore.js
src/createViewer.js

Detect when we have only a labelmap and make adjustments to how user-
specified weights (from the labelmap piecewise function slider) are
mapped to the actual pwf.  Also, adjust weight->pwf mapping when we
are showing slice compared to volume, as we always want some context
in slice mode (so we can see segments to adjust pwf for).
Decouple the component selection checkboxes from the labelmap weight
slider, as those do not interact well together.  After this change,
the component visibility state consists of a boolen indicating whether
the component is shown or hidden, as well as float specifying the
weight.
Depends on this [change](https://github.com/Kitware/vtk-js/pull/1473) in `vtk.js`.

fix(viewer): Various rendering/ui improvements

---

src/UserInterface/createFileDragAndDrop.js
src/index.js

Suggested-by: Wei Ouyang <oeway007@gmail.com>

feat(createFileDragAndDrop): Return Promise that supplies created viewer

---

src/Rendering/updateComponentPiecewiseFunction.js
src/UserInterface/Image/createComponentSelector.js
src/UserInterface/Image/createTransferFunctionWidget.js
src/UserInterface/Image/updateTransferFunctionHistogramValues.js
src/UserInterface/Image/updateTransferFunctionLookupTable.js
src/UserInterface/Image/updateTransferFunctionWidget.js
src/ViewerStore.js
src/createViewer.js

Exposes `opacityGaussiansChanged` and `componentVisibilitiesChanged` events, as well as api to set/get those properties.

Expose more viewer features via api

---

src/UserInterface/Image/createComponentSelector.js

style(ComponentSelector): More spacing in tabs

---

src/UserInterface/Image/createTransferFunctionWidget.js
src/UserInterface/Image/updateTransferFunctionHistogramValues.js
src/ViewerStore.js

Based on the component data range.
Suggested-by: Alexis Girault <alexis.girault@kitware.com>

feat(transferFunctionRangeManipulator): Per-component motion scaling

---

src/UserInterface/ItkVtkViewer.module.css
src/UserInterface/addLogo.js

Suggested-by: Will Schroeder <will.schroeder@kitware.com>

doc(Logo): Add app attribution paragraph on click

---

src/Rendering/applyPiecewiseFunctionOpacities.js
src/Rendering/createImageRendering.js
src/Rendering/filterAndProcessOpacityNodes.js
src/Rendering/updateComponentPiecewiseFunction.js
src/Rendering/updateSliceProperties.js
src/Rendering/updateVolumeProperties.js
src/UserInterface/Image/createColorRangeInput.js
src/UserInterface/Image/updateTransferFunctionWidget.js

Should fix the color out-of-range issues we have seen with 2 or more components.

fix(SliceRendering): Fix color out of range issues for 2+ components

---

src/Rendering/applyPiecewiseFunctionOpacities.js
src/UserInterface/Geometries/createGeometryColorRangeInput.js
src/UserInterface/Geometries/createGeometryColorWidget.js
src/UserInterface/Image/updateTransferFunctionHistogramValues.js
src/UserInterface/Image/updateTransferFunctionLookupTable.js
src/UserInterface/PointSets/createPointSetColorRangeInput.js
src/UserInterface/PointSets/createPointSetColorWidget.js
src/UserInterface/createGeometriesUI.js
src/UserInterface/createPointSetsUI.js
src/UserInterface/rgb2hex.js

Asynchronous and varied initialization triggers some interesting behaviour. Hardening.

Geometries fixes part 2

---

package.json

build(DevServer): Open browser tab with npm start

---

dist/index.html
doc/content/docs/imjoy.md
src/utils.js
test/imjoyTest.js

Fixes https://github.com/Kitware/itk-vtk-viewer/issues/344 and support displaying 3D color image.

feat(ImJoy): Support numpy array and 3D color image

---

src/UI/Reference/Images/applyColorMap.js
src/UI/Reference/Images/applyLookupTable.js
src/UI/Reference/Images/createTransferFunctionWidget.js
src/UI/Reference/Images/selectImageComponent.js
src/UI/Reference/Images/updateRenderedImageInterface.js

- fix(selectImageComponent): Update per-component information
- fix(updateRenderedImageInterface): Apply pwf to all visualized components

multi component select

---

doc/content/config/index.md
src/Context/ViewerMachineContext.js
src/Rendering/VTKJS/createRenderer.js
src/Rendering/VTKJS/vtk/ItkVtkViewProxy.js
src/UI/Reference/Layers/selectLayer.js
src/createViewer.js
test/createViewerTest.js
test/imjoyTest.js

- refactor(ViewerMachineContext): Remove unused slicingPlanesEnabled
- feat(Config): Add xyLowerLeft option
- feat(Config): Add uiCollapsed

xylowerleft

---

src/Rendering/Images/createImageRenderingActor.js

Have a reasonable limit for rendering.

fix(ImageRenderingActor): Multiscale rendering constraint on number of pixels

---

doc/content/api/index.md
src/imJoyPluginAPI.js
test/imjoyTest.js

This PR enables `viewer.captureImage()` API for ImJoy.

feat(ImJoy): Expose captureImage API

---

README.md

Remove required browser versions because they are not tested.

doc(README): Update required Node/NPM versions

---

package.json
src/Context/ViewerMachineContext.js
src/IO/fetchBinaryContent.js
src/IO/toMultiscaleChunkedImage.js

- build(startScript): Use port that does not conflict with default ipfs gateway port
- fix(ViewerMachineContext): Proceed with null config
- feat(fetchBinaryContent): Support ipfs: protocols

legacy format ipfs

---

package-lock.json
package.json
src/UI/reference-ui/package-lock.json
src/UI/reference-ui/package.json
src/UI/reference-ui/src/Images/applyColorMap.js
src/UI/reference-ui/src/Images/applyLookupTable.js
src/UI/reference-ui/src/Images/createColorRangeInput.js
src/UI/reference-ui/src/Images/createGradientOpacitySlider.js
src/UI/reference-ui/src/Images/createLabelImageColorWidget.js
src/UI/reference-ui/src/Images/createLabelImageWeightWidget.js
src/UI/reference-ui/src/Images/createSampleDistanceSlider.js
src/UI/reference-ui/src/Images/createTransferFunctionWidget.js
src/UI/reference-ui/src/Images/selectImageComponent.js
src/UI/reference-ui/src/Images/updateImageInterface.js
src/UI/reference-ui/src/Images/updateRenderedImageInterface.js
src/UI/reference-ui/src/Main/createCroppingButtons.js
src/UI/reference-ui/src/Main/createPlaneSliders.js
src/UI/reference-ui/src/applyCategoricalColorToLookupTableProxy.js
src/UI/reference-ui/src/vtk/ItkPiecewiseGaussianWidget.js
src/UserInterface/applyCategoricalColorToLookupTableProxy.js

Incorporates patches for the esm build.

build(Dependencies): Update vtk.js to 19.0.2

---

README.md

doc(README): Remove Dependency Status badge

---

src/IO/Downsample/Downsample.cxx
src/IO/Downsample/package-lock.json
src/IO/Downsample/package.json
src/Rendering/VTKJS/Main/updateFps.js

- fix(updateFps): Use Interactor recentAnimationFrameRate
- fix(Downsample): Support Vector<uint8_t, 3>

fps computation

---

src/IO/fetchBinaryContent.js

fix(fetchBinaryContent): Support relative URLs

---

src/itkConfigCDN.js

__itk_viewer_version__ -> __itk_vtk_viewer_version__

fix(itk config): webpack defined variable typo

---

package-lock.json
package.json
src/index.d.ts
tsconfig.json

Some rough types for src/index.js
closes #461

chore(types): add top level Typescript types

---

src/IO/ZarrMultiscaleChunkedImage.js
src/index.js

- fix(createViewerFromUrl): url undefined for image, labelImage
- fix(isZarr): Support DANDI urls

dandi zarr

---

src/IO/ZarrMultiscaleChunkedImage.js

fix(ngff zarr): ngff zarr to viewer dimension mapping bug

---

src/IO/processFiles.js
src/createViewer.js
src/index.js
test/createViewerTest.js

A test:
http://localhost:8082/?image=https://dandiarchive.s3.amazonaws.com/zarr/3d313fc2-0204-496d-bfa1-5c90951ee640&gradientOpacity=.3

feat(url parameters): add gradientOpacity url param option

---

README.md

doc(README): Update required Node version to 12+

---

.github/workflows/build-test.yml

Testing data has been pinned there too for reliability and speed.

ci(Data): Connect to pinata.cloud hosts

---

dist/index.html
doc/content/docs/imjoy.md
src/IO/ndarrayToItkImage.js
src/IO/toMultiscaleSpatialImage.js
src/imJoyCodecs.js
src/index.js

- feat(ndarrayToItkImage): Use itk-wasm types, add 64bit int support
- doc(ImJoy): itk.js -> itk-wasm
- feat(imJoy): Add Codec for decoding itk-wasm Image from itkwidgets

itkwidgets type support

---

src/index.js

fix(processURLParameters): fileToLoad param not triggering createViewerFromUrl

---

karma.conf.js
package-lock.json
src/IO/ZarrMultiscaleSpatialImage.js
src/Rendering/VTKJS/Images/applyRenderedImage.js
src/Rendering/VTKJS/vtk/ItkVtkViewProxy.js
test/createViewerTest.js

If top level `.zattrs` has `multiscaleSpatialImageVersion`, get `long-name` from axis `.zattrs`
Also pull direction and range from image `.zattrs` if top level has `multiscaleSpatialImageVersion`
closes #484

feat(axes labels): fetch and show long axes names

---

package-lock.json
package.json

Avoids downstream packaging errors when importing referenceUI source.

fix(scaleSelect): sync root itk-viewer-icons version with referenceUI

---

src/createViewer.js
src/imJoyPluginAPI.js

Add `setLabelImage` and `getLabelImage` functions to both the viewer and ImJoy plugin API.

Set label image

---

package-lock.json
package.json
src/Rendering/VTKJS/Images/applyRenderedImage.js
src/Rendering/VTKJS/Main/applyCroppingPlanes.js
src/Rendering/VTKJS/Main/croppingPlanes.js
src/UI/reference-ui/dist/referenceUIMachineOptions.js
src/UI/reference-ui/package-lock.json
src/UI/reference-ui/package.json
src/UI/reference-ui/src/Images/applyImagesContrastSensitiveStyle.js
src/UI/reference-ui/src/Images/scaleSelector.js
test/downloadData.mjs

Fixes #513
Updates vtk.js version to pickup fix to cropping plane normal calculation in ImageMapper via https://github.com/Kitware/vtk-js/pull/2512
Computes merged actors' bounding box in image oriented space.
Fixes "scale selector" icon not changing to white color when viewer starts with a dark background.
Adds the LIDC2.mha file to the test data.

Cropping Planes fix when rotated image

---

src/Rendering/Images/createImageRenderingActor.js
src/UI/Images/createImagesUIMachine.js
src/UI/reference-ui/dist/referenceUIMachineOptions.js
src/UI/reference-ui/src/Images/scaleSelector.js

feat(scaleSelector): option to Framerate-pick in dropdown

---

src/Rendering/VTKJS/Main/takeScreenshot.js
src/createViewer.js
src/createViewerMachine.js
src/imJoyPluginAPI.js

Needed for PR InsightSoftwareConsortium/itkwidgets#448, issue InsightSoftwareConsortium/itkwidgets#445

Emit a signal with the screenshot png when one is generated

---

src/createViewer.js
src/imJoyPluginAPI.js

ENH: Add capabilities for changing UI - refactor

---

src/Rendering/VTKJS/Images/applyRenderedImage.js

Fixes having a label map and starting with slice rendering via use2D=true
closes #502

fix(applyRenderedImage): synchronously set label map lookup table

---

dist/testConglomerate.html
src/IO/ConglomerateMultiscaleSpatialImage.js
src/IO/MultiscaleSpatialImage.js
src/Rendering/Images/createImageRenderingActor.js
src/Rendering/Images/createImagesRenderingMachine.js
src/Rendering/VTKJS/Images/imagesRenderingMachineOptions.js
src/Rendering/VTKJS/Images/updateRenderedImage.js
src/Rendering/VTKJS/Main/croppingPlanes.js
src/UI/Layers/createLayersUIMachine.js

Big change to the `ImageRenderingActor`

Automatically pick finer or coarser scale when changing bounds

---

.github/workflows/build-test.yml

https://github.com/actions/runner-images/issues/5583

chore(build-test): bump macos version to supported

---

src/Rendering/Images/createImageRenderingActor.js
src/Rendering/Images/createImagesRenderingMachine.js
src/Rendering/Images/makeTransitions.js
src/Rendering/Main/createMainRenderingMachine.js
src/Rendering/VTKJS/Images/applyRenderedImage.js
src/Rendering/VTKJS/Main/computeRenderedBounds.js
src/Rendering/VTKJS/Main/mainRenderingMachineOptions.js
src/Rendering/VTKJS/Main/updateSlicingPlanes.js

fix(Slice Planes): bound slice planes min-max by cropping planes

---

package-lock.json
package.json
src/IO/ZarrMultiscaleSpatialImage.js

Prevents the network from getting overwhelmed trying to handle all of the promises at once for higher resolution levels. For larger data there may be quite a few chunks and if overwhelmed the data may not load the full resolution.

fix(zarrmultiscalespatialimage): use a promise queue to manage resolving chunk promises

---

src/Context/ImageActorContext.js
src/Rendering/VTKJS/Images/applyCinematicChanged.js
src/Rendering/VTKJS/Main/toggleCroppingPlanes.js
src/UI/reference-ui/dist/referenceUIMachineOptions.js
src/UI/reference-ui/src/Images/cinematic.js

and handles got lighting disabled

Volumetric scattering blending

---

dist/index.html
src/ImJoyPluginAPI.js
src/index.js

Also mark set up as async.
To facilitate use with hypha.

feat(ImJoyPluginAPI): Change to a class

---

src/UI/reference-ui/dist/referenceUIMachineOptions.js
src/UI/reference-ui/package-lock.json
src/UI/reference-ui/package.json
src/UI/reference-ui/src/Images/cinematic.js
src/UI/reference-ui/src/ItkVtkViewer.module.css

feat(cinematic): add volume scattering blend icon

---

src/UI/reference-ui/dist/referenceUIMachineOptions.js
src/UI/reference-ui/src/ItkVtkViewer.module.css
src/UI/reference-ui/src/Main/createBackgroundColorButton.js
src/UI/reference-ui/src/Main/createResetCameraButton.js
src/UI/reference-ui/src/createColorMapIconSelector.js
src/UI/reference-ui/src/createInterface.js
src/UserInterface/Geometries/createGeometryRepresentationSelector.js

For Reference-UI: moves ColorMapIconSelector popout box left and down to avoid getting clipped when it extends over the right boundary of the sidebar. Also, have to have right side tooltips pop left.  Not ideal.

fix(sidebar): scroll bar shows with small height

---

dist/test-pointsets.html
src/UI/reference-ui/dist/referenceUIMachineOptions.js
src/UI/reference-ui/src/ItkVtkViewer.module.css
src/UI/reference-ui/src/createColorMapIconSelector.js
src/UserInterface/addLogo.js
test/createViewerTest.js

Also:
* fix clicking logo for credits and FPS
* fix error setting up pointsets in tests.  Gets one of the cases of #590

fix(sidebar): allow clicking under sidebar to 3D canvas

---

src/UI/Layers/createLayersUIMachine.js

Set first 4 component colormaps to red, green, blue, gray instead of CT-AAA when more than 4 components
http://localhost:8082/?image=https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.4/idr0101A/13457537.zarr

feat(createLayersUIMachine): for 4 or more components colormap RGB+Gray

---

doc/content/api/index.md
src/Rendering/VTKJS/Images/applyRenderedImage.js
src/createViewer.js

feat(createViewer): disable 2D interpolation if label image

---

src/Rendering/VTKJS/Images/applyRenderedImage.js
src/Rendering/VTKJS/vtk/ItkVtkViewProxy.js

So that is is not blocked by the plane sliders in smaller views
Old:
New:

feat(CornerAnnotation): Move corner annotation SE -> NE

---

src/Rendering/VTKJS/createRenderer.js
src/UI/Images/transferFunctionManipulators.js

New PR for gesture manipulator implementation.  Can "pinch to zoom" now.
this PR fixes issue: https://github.com/Kitware/itk-vtk-viewer/issues/562

feat(itkVtkViewProxy): add touch camera manipulator

---

.github/workflows/publish.yml

chore(ci): fix publish workflow test data URL

---

src/ImJoyPluginAPI.js

`getRenderingViewStyle` -> `getRenderingViewContainerStyle`

fix(imjoypluginapi): fix rendering style fn: 

---

src/ImJoyPluginAPI.js

The previous conditions restricted the viewer creation to setting only an image or point set. Update the conditional flow so that any data passed is always set.
This should also fix the issue seen in InsightSoftwareConsortium/itkwidgets#606

fix(imjoypluginapi): refactor run to support setting multiple data types

---

README.md

docs(README): Update Node min version to 16

---

src/Rendering/Images/createImageRenderingActor.js
src/Rendering/VTKJS/Images/updateHistogram.js
src/UI/reference-ui/dist/referenceUIMachineOptions.js
src/UI/reference-ui/src/Layers/compareUI.js

feat(compare): show swap image button next to image mix slider

---

src/Rendering/VTKJS/vtk/ItkVtkViewProxy.js

Firefox bug https://bugzilla.mozilla.org/show_bug.cgi?id=941146

fix(ItkVtkViewProxy): workaround Firefox bug with canvas

---

src/Context/ImageActorContext.js
src/Rendering/Images/createImageRenderingActor.js

fixes https://github.com/InsightSoftwareConsortium/itkwidgets/issues/666
fixes https://github.com/InsightSoftwareConsortium/itkwidgets/issues/661

Fix default compare method and color range not updated during compare

---

examples/test-conglomerate.html
package-lock.json
package.json
src/Context/ImageActorContext.js
src/ImJoyPluginAPI.js
src/Rendering/Images/createImageRenderingActor.js
src/Rendering/Images/createImagesRenderingMachine.js
src/Rendering/VTKJS/Images/applyRenderedImage.js
src/Rendering/createRenderingMachine.js
src/UI/Layers/createLayersUIMachine.js
src/createViewer.js
src/createViewerMachine.js

Min max color range source of truth is still colorRange array, but we the auto adjust boolean bookkeeping is per min and max. Was just one boolean for colorRange before.

feat(createImageRenderingActor): add color range min/max
