Kitware/itk-vtk-viewer

src/ItkVtkViewProxy.js

When picking on the slices. Addresses picking from 2D images and impacts
the picked value.
Co-authored-by: Sebastien Jourdain <sebastien.jourdain@kitware.com>
Co-authored-by: Alexis Girault <alexis.girault@kitware.com>
@agirault @jourdain it worked :1st_place_medal:

fix(ItkVtkViewProxy): Use vtkPointPicker instead of vtkCellPicker

---

package.json

For publishing. The GIT_PUBLISH_URL is setup in .travis.yml. Use for
repositoryUrl if set.
This helps semantic-release pick up the correct publish URL.
As documented:
https://github.com/semantic-release/semantic-release/blob/caribou/docs/usage/configuration.md#repositoryurl

ci(semantic-release): Specify repositoryUrl

---

.travis.yml
karma.conf.js
package.json

This did not work. We not run WebGL tests on Azure Pipelines.
Closes #89

test(Travis): Remove test:travis script

---

src/userInterface/ItkVtkViewer.module.css

Fixes a specific, annoying issue where the "Volume Spacing Distance" and "Gradient Opacity" tooltips pop up and block interactions with the windowing canvas. This fix makes the tooltips only popup when hovering over the relevant icons.
Tested on Firefox 66.0.3 x64 on Windows 10

Fix tooltips blocking interactions

---

.travis.yml
azure-pipelines.yml

This is the preferred command for deployment that uses package-lock.json.

ci(npm): Use npm ci instead of npm install

---

.travis.yml

A workaround for: https://travis-ci.community/t/npm-ci-will-fail-if-cached-dependency-includes-npm/4203

ci(Travis): Use npm install

---

src/ItkVtkViewProxy.js

This preserves a high quality volume rendering when the mouse is moving
over the volume. We still request animation when the slicing planes are
enabled so the cursor widget is updated.

fix(ItkVtkViewProxy): Do not animate when mouseover volume rendering

---

src/ItkVtkViewProxy.js
src/UserInterface/createImageUI.js
src/UserInterface/createMainUI.js
src/createViewer.js
src/index.js
src/processFiles.js
src/utils.js

Not sure how you would do this, but with this PR, I am trying to extract utility functions and export it such that it will be much easier to customize the viewer. 
For now, `itkVtkViewer.utils` has:
* `readFiles` for reading files into VTK image
* `convertItkToVtkImage` for converting user data into a VTK image
*  `UserInterface` for customize the user interface, for example recreate the MainUI in another containier outside the viewer.
With these extracted functions and additions to existing api, I would like to:
1. be able to load a file object locally or fetched remotely with `utils.readFiles`
2. construct an ITK image for the veiwer with `convertItkToVtkImage`
3. create the MainUI in a custom container which will likely outside the root container of the viewer
4. be able to recreate …

Export utility functions for customizing the viewer

---

src/ItkVtkViewProxy.js

This PR aims to address https://github.com/Kitware/itk-vtk-viewer/issues/240 by adding a class to the corner annotation such that a developer can do something like:
```css
.corner-annotation {
font-size: 2rem;
color: gray;
}
```
to customize the corner annotation.

Add css class for styling corner annotation

---

src/UserInterface/Image/createTransferFunctionWidget.js

By adjusting the default `xBias` used to initialize the piecewise functions, we can make sure the function does not drop to near zero at the max end of the data range.
Fixes #246

fix(Viewer): Make piecewise function cover max

---

src/CoordDecompressor.js
src/Rendering/index.js
src/Rendering/updateSliceProperties.js
src/Rendering/updateVolumeProperties.js
src/UserInterface/Image/createComponentSelector.js
src/UserInterface/Image/createTransferFunctionWidget.js
src/UserInterface/ItkVtkViewer.module.css
src/UserInterface/createImageUI.js
src/ViewerStore.js
src/bloscZarrDecompress.js
src/createViewer.js
src/processFiles.js

This is coming along.  Still needed:

WIP: Replace lut pwf select with tabs

---

src/index.js

Adding support for passing two comma-separated urls in the `fileToLoad` url parameter broke the url handling when embedding the viewer in another application and using the `data-url` attribute to specify the location of the data.  This fixes that, extending the support for providing comma-separated urls in the embedded use case.

fix(Viewer): Fix broken url handling in embedded case

---

src/UserInterface/Geometries/createGeometryOpacitySlider.js

As suggested by @thewtex in PR #270, I apply the same changes to handle the opacity default value. I let the default value to 1.0 since it is perhaps more std in the general use. But changing the default value make well change the first opacity. I tested here: http://ipol-geometry.loria.fr/~kerautre/ipol_demo/LiverVesselnessIPOLDemo/result?key=E06650B089BFFDD6C31AC33C901556E8

fix(createGeometryOpacitySlider): apply default geometry opacity

---

src/Rendering/createLabelMapRendering.js
src/UserInterface/Main/createInterpolationButton.js

This PR fixes the regression with the interpolation button being enabled, even when we we have a labelmap, as well as some issues we saw last week with lots of labels seemingly getting assigned the same color, even though mouse picking could distinguish the labeled regions.

Fix issue affecting labemaps with many labels

---

src/processFiles.js

The first labelmap-like image is used from file(s)ToLoad if a labelmap has not been
specified explicitly. The first image specified is used if one has not
been specified explicitly.

fix(processFiles): Correct logic for detecting label maps

---

src/Rendering/updateLabelMapComponentWeight.js
src/ViewerStore.js

When a label map is not present, avoid falsely suppressing the intensity
image.

fix(updateLabelMapComponentWeight): Update only when label map present

---

src/UserInterface/Geometries/createGeometryColorBySelector.js
src/UserInterface/Geometries/createGeometryColorRangeInput.js
src/ViewerStore.js

The vtk.js AbstractRepresentationProxy sets the Mapper ColorMode to
MAP_SCALARS if scalars and a lookup table proxy are present, but we always
have a lookup table proxy. Set ColorModeToDefault on the Mapper and high
lookup table GUI elements with 3-component unsigned char scalars.

fix(Geometries): Support direct unsigned char scalar colors

---

src/UserInterface/Image/createColorRangeInput.js

In itkwidgets, one of the values can be undefined if only vmin or vmax
is set.

fix(ColorRangeInput): Only set values when both min max defined

---

package-lock.json
package.json

Adds https://github.com/Kitware/vtk-js/pull/1512 to address:
https://github.com/Kitware/itk-vtk-viewer/issues/310
For single component images.

fix(PiecewiseFunction): Bump vtk.js to 14.8.1

---

src/createViewer.js

This technically a breaking change, but this is required to:
- Use a consistent event name.
- Avoid emitting too often when the selected component index changes.
- mobx emits a warning during initialization when accessing an empty
value (how this was discovered).

fix(colorRangesChangedEvent): Fix emission

---

src/Rendering/createImageRendering.js
src/Rendering/updateGradientOpacity.js
src/Rendering/updateLabelMapComponentWeight.js
src/Rendering/updateSliceProperties.js
src/Rendering/updateVolumeProperties.js
src/UserInterface/Image/createColorRangeInput.js
src/UserInterface/Image/createComponentSelector.js
src/UserInterface/Image/createTransferFunctionWidget.js
src/UserInterface/Image/updateTransferFunctionHistogramValues.js
src/UserInterface/Image/updateTransferFunctionWidget.js
src/UserInterface/ItkVtkViewer.module.css
src/UserInterface/createImageUI.js
src/ViewerStore.js
src/createViewer.js

Add support for when images have more components that we can visualize at one time.
This is getting close, some remaining items:

WIP: Fixes for many component images

---

src/Rendering/VTKJS/Images/applyRenderedImage.js

Otherwise an Array reference is sent and all components end up with the
range of the last component.

fix(applyRenderedImage): Create a copy of the color range before sending

---

webpack.config.js

With this PR we will be able to use the produce node module like this:
```js
import * as itkVtkViewer from "itk-vtk-viewer";
```
I am not sure whether this is the best way to do it, but I generate umd module for my other projects.

fix(WebPack): Produce UMD library target

---

src/UI/Layers/createLayersUIMachine.js

Do not make an implicit assumption so independentComponents can be
enabled via pixelType.

fix(independentComponents): Require explicit RGB or RGBA pixelType

---

doc/content/api/index.md
src/Context/ImagesMachineContext.js
src/UI/Reference/toggleUICollapsed.js
src/createViewer.js
src/imJoyPluginAPI.js
test/createViewerTest.js

- feat(API): Add selectLayer
- fix(imjoyPluginAPI): Add setLayerVisibility, getLayerVisibility
- fix(UI): Select image layer when UI in un-collapsed (closes https://github.com/Kitware/itk-vtk-viewer/issues/375)
- refactor(createViewer): Disable debug statements

select layer

---

package.json
src/index.js
webpack.config.js

- fix(NPM): Run Webpack build during prepublishOnly
- fix(index): Export the package version
- fix(Webpack): Use the itk-vtk-viewer Unpkg for the CDN path

version cdn

---

src/Rendering/VTKJS/Images/applyRenderedImage.js

All channels should have the same range for dependent components. Avoid
divide by 0 when the min/max range are the same.
Closes #380

fix(applyRenderedImage): Default range for dependent components, no range

---

src/index.js

`setUserInterfaceCollapsed` was refactored to `setUICollapsed` here:
b3b74272666d8d200f7c3461bbc4c2c6fd2d4707

fix(index.js): replace deleted function setUserInterfaceCollapsed for setUICollapsed

---

package.json

Following instructions from https://github.com/commitizen/cz-cli

fix(package.json): fix commitizen config path to allow working with globally installed package

---

webpack.config.js

This should help with the ImJoy tests when `npm run build` is not run
before `npm test`.

build(Webpack): Enable devServer writeToDisk

---

test/run.sh

Updates:
- Chrome 88.4324.182
- Firefox 86
- Node 12.21.0
- NPM 6.14.11

test(Docker): Bump CI image for Ubuntu 20.04

---

src/Rendering/VTKJS/vtk/ItkVtkViewProxy.js

For small values, e.g.
2.0540516842970646e-8
this was being truncated as
2.054

fix(CornerAnnotation): Fix position precision truncation

---

src/Rendering/VTKJS/createRenderer.js

Required with vtk.js 18 and later.

fix(createRenderer): Load vtk.js rendering profiles

---

src/IO/ndarrayToItkImage.js

`itk-wasm` expects that direction have a float array set directly on the key rather than the old approach of setting the array within a data object.

fix(ndarraytoitkimage.js): directly set direction as Float32 arrays

---

src/Rendering/VTKJS/Images/applyRenderedImage.js

The window is too large, otherwise, making the image appear dim.
VTK.js has a different state setup for 3D that makes this necessary. Use this
approach for now.

fix(2DImageRendering): Set color level, color window

---

src/UI/Images/createImagesUIMachine.js
test/createViewerTest.js

If custom config does not include uiMachineOptions.images.services.scaleSelector
there is an state machine error:
Error: Unable to send event to child 'scaleSelector' from service 'images'.
This change provides default stub for the scaleSelector
closes #516

fix(scaleSelector): error when uiMachineOptions missing scaleSelector

---

src/IO/ndarrayToItkImage.js

fix(ndarraytoitkimage): support boolean arrays. Cast to uint8

---

src/Rendering/VTKJS/Images/FuseComponents.worker.js
src/Rendering/VTKJS/Images/fuseImages.js
src/Rendering/VTKJS/Images/updateRenderedImage.js
src/Rendering/VTKJS/Images/updateVisualizedComponents.js
src/UI/Images/createImagesUIMachine.js

When 4 components were ON and user clicked checkbox of OFF component,
sometimes it turned on, sometimes it did not.  Fixed.
If new fused image takes some time to build in worker and user changes
rendering parameters of current image, there would be an error as the
current image buffer was transferred to worker.  Changed to no longer transfer array.

Fixes for fuseComponents and component checkbox UI

---

.github/workflows/build-test.yml
.github/workflows/publish.yml

The IPFS node has difficulty downloading the data without a timeout.
This may be due to starting up the node and immediately requesting large
amounts of data without the opportunity to provide data to peers.
Download and extract a versioned tarball for now from GitHub Releases.
In the future, we will look to download a versioned, provenance rich
DataLad dataset.

ci(Data): Use tarball for CI fetch

---

src/Rendering/VTKJS/Images/applyRenderedImage.js
src/Rendering/VTKJS/Main/croppingPlanes.js

Allows for grabbing of crop plane handles "through" the volume bounding box.  
Sad effect is can click on handles even if they are totally occluded by the volume!
Alternatives:
- change appearance of handles when on other side of volume
- fix vtk.js picking (click through volume opacity threshold?)

fix(croppingPlanes): disable picking on volume actor

---

src/IO/MultiscaleSpatialImage.js

Before was keeping images that were not fully contained by new image.
closes #543

fix(MultiscaleSpatialImage): cache only one image per scale

---

package-lock.json
package.json
src/Context/ImageActorContext.js
src/Rendering/Images/createImageRenderingActor.js
src/Rendering/VTKJS/Images/applyRenderedImage.js
src/Rendering/VTKJS/Images/imagesRenderingMachineOptions.js
src/Rendering/VTKJS/Images/updateRenderedImage.js
src/Rendering/VTKJS/Main/croppingPlanes.js
src/UI/Images/createImagesUIMachine.js
src/UI/Layers/createLayersUIMachine.js
src/UI/createUIMachine.js
src/UI/reference-ui/dist/referenceUIMachineOptions.js
src/UI/reference-ui/package-lock.json
src/UI/reference-ui/package.json
src/UI/reference-ui/src/Images/scaleSelector.js
src/createViewer.js
src/createViewerMachine.js

Update scale drop-down to last successfully loaded scale after error loading user selected scale.
Good test case:
http://localhost:8082/?rotate=false&image=https://dandiarchive.s3.amazonaws.com/zarr/3d313fc2-0204-496d-bfa1-5c90951ee640
Then select scale 3 for "Out of memory error transferring to worker" or scale 2 for "to many network requests" error.
closes #544

fix(createImageRenderingActor): handle errors making new image scale

---

src/Rendering/VTKJS/Images/createImageRenderer.js
src/Rendering/VTKJS/vtk/ItkVtkViewProxy.js
src/Rendering/VTKJS/vtk/OpenGLImageMapperFractional.js
src/Rendering/VTKJS/vtk/WidgetManagerPickWhileAnimating.js

Add subclassed WidgetManager to handle events even when interactor is
animating (like with FPS speed checks or auto rotating).
The FPS speed check after each crop handle change triggered the renderWindow.interactor
to be animating which disabled the WidgetManager from handling events.

fix(ItkVtkViewProxy): grab crop handles when animating

---

src/Rendering/Images/createImageRenderingActor.js
src/Rendering/Images/createImagesRenderingMachine.js
src/Rendering/VTKJS/Images/applyRenderedImage.js
src/Rendering/VTKJS/Images/assignRenderedImage.js
src/Rendering/VTKJS/Images/imagesRenderingMachineOptions.js
src/Rendering/VTKJS/Images/updateRenderedImage.js
src/Rendering/createRenderingMachine.js
src/createViewerMachine.js

User set bounds and scale could get out of sync with rendering.  Steps:
1. Trigger slow updateRenderedImage by setting super fine scale.
2. Trigger fast updateRenderedImage by setting coarse or cached scale.
3. Fast updateRenderedImage sets rendering, then stale slow updateRenderedImage
overrides the more up to date updateRenderedImage result.
Update context and the rendering after updateRenderedImage Promise
resolves.  Promise result is ignored if loadingImage
state has been exited.

fix(ImageRenderingActor): ignore stale updateRenderedImage results

---

src/imJoyPluginAPI.js

From `itkwidgets` allows users to create an empty viewer before setting any data. For example:
```
viewer = view()
viewer.setImage(img)
```

feat(imjoyplugin): support creation of empty viewer

---

src/createViewer.js

If `setImage` is called with no previous data set the image name is `undefined` which creates errors further down the pipeline. Always use a string as the image name.

fix(setimage): prevent image name from being set to undefined

---

src/Context/ImageActorContext.js
src/Context/MainMachineContext.js
src/IO/ConglomerateMultiscaleSpatialImage.js
src/IO/MultiscaleSpatialImage.js
src/Rendering/Images/createImageRenderingActor.js
src/Rendering/Images/createImagesRenderingMachine.js
src/Rendering/VTKJS/Images/applyColorRangeBounds.js
src/Rendering/VTKJS/Images/applyRenderedImage.js
src/Rendering/VTKJS/Images/applyVolumeSampleDistance.js
src/Rendering/VTKJS/Images/assignRenderedImage.js
src/Rendering/VTKJS/Images/fuseImages.js
src/Rendering/VTKJS/Images/imagesRenderingMachineOptions.js
src/Rendering/VTKJS/Images/mapToPiecewiseFunctionNodes.js
src/Rendering/VTKJS/Images/updateHistogram.js
src/Rendering/VTKJS/Images/updateRenderedImage.js
src/Rendering/VTKJS/Main/computeRenderedBounds.js
src/Rendering/VTKJS/Main/croppingPlanes.js
src/Rendering/VTKJS/proxyManagerConfiguration.js
src/Rendering/createRenderingMachine.js
src/UI/Images/createImagesUIMachine.js
src/UI/Layers/createLayersUIMachine.js
src/UI/reference-ui/dist/referenceUIMachineOptions.js
src/UI/reference-ui/src/Images/applyColorRange.js
src/UI/reference-ui/src/Images/applyColorRangeBounds.js
src/UI/reference-ui/src/Images/createTransferFunctionEditor.js
src/UI/reference-ui/src/Images/selectImageComponent.js
src/UI/reference-ui/src/Images/throttle.js
src/createViewer.js
test/createViewerTest.js

For the world bounds passed to `MultiscaleSpatialImage.getImage()`, `updateRenderedImage()` intersects the world axis aligned bounding box of the camera frustum with the cropping planes.  Camera modified events trigger `updateRenderedImage()` after debounce.
Changes colorRange and colorRangeBounds to automatically grow after loading more image data.  As image scales become finer, intensity extremes emerge. If the colorRange/colorRangeBounds are changed by the UI or API, they are "touched" and don't automatically change as new data is loaded. Before was calculating the range of data just once on the coarsest scale.  However, that may have had a better result for visualization by clipping the extremes in the transfer functions.

Load image bounded by camera frustum

---

src/Rendering/Images/createImageRenderingActor.js
src/Rendering/VTKJS/Images/updateRenderedImage.js
src/UI/Layers/createLayersUIMachine.js

Fixes bugs when rotate=true and data has preset ranges.
When rotate=true, ImageRenderingActor machine would switch out of loading state to camera debouce state and thus ignore return value of updateRenderedImage.  Would never apply the loaded image.
If the data had colorRanges preset, Layer machine would set actorcontext.colorRanges, but no change would be detected in applyRendereImage and the transfer function objects applyRendereImage creates would not get updated.

Rotate and color ranges bugs

---

dist/testConglomerate.html
src/Rendering/VTKJS/Images/applyColorMap.js
src/Rendering/VTKJS/Images/applyRenderedImage.js
src/Rendering/VTKJS/Images/updateVisualizedComponents.js
src/UI/Layers/createLayersUIMachine.js
src/UI/reference-ui/dist/referenceUIMachineOptions.js
src/UI/reference-ui/src/Layers/selectLayer.js
src/createViewer.js
test/createViewerTest.js

Fixes case when setImage and setLabelImage happen after createViewer
```
const viewer = await itkVtkViewer.createViewer(container)
viewer.setImage(image)
viewer.setLabelImage(labelImage)
```

If image loaded after labelImage, reuse actorContext

---

src/Rendering/Images/createImageRenderingActor.js
src/Rendering/VTKJS/Images/applyRenderedImage.js
src/Rendering/VTKJS/Images/fuseImagesUtils.js
src/Rendering/VTKJS/Main/applyXSlice.js
src/Rendering/VTKJS/Main/applyYSlice.js
src/Rendering/VTKJS/Main/applyZSlice.js
src/Rendering/VTKJS/renderLater.js
src/Rendering/VTKJS/vtkJSRenderingMachineOptions.js
src/Rendering/createRenderingMachine.js
src/createViewerMachine.js

After adding this line
https://github.com/Kitware/itk-vtk-viewer/blob/67915784ef42d03e21c5c8e4b69f980352e7990f/src/Rendering/VTKJS/Images/applyRenderedImage.js#L134
Slider steps were updated every scale to the image spacing.  Synchronous window.render calls became bottlenecks.  This PR changes to asynchronous render calls.
Also catches more out of memory errors when loading images.

Laggy Slice Slider Fix and Out of Memory Catching

---

package-lock.json
package.json
src/Context/ImageActorContext.js
src/Rendering/Images/createImageRenderingActor.js
src/Rendering/Images/createImagesRenderingMachine.js
src/Rendering/VTKJS/Images/applyCinematicChanged.js
src/Rendering/VTKJS/Images/imagesRenderingMachineOptions.js
src/Rendering/VTKJS/vtk/ItkVtkViewProxy.js
src/Rendering/createRenderingMachine.js
src/UI/Images/createImagesUIMachine.js
src/UI/createUIMachine.js
src/UI/reference-ui/dist/referenceUIMachineOptions.js
src/UI/reference-ui/package.json
src/UI/reference-ui/src/Images/cinematic.js
src/UI/reference-ui/src/Images/createSampleDistanceSlider.js
src/UI/reference-ui/src/Images/createVolumeRenderingInputs.js
src/UI/reference-ui/src/Images/imagesUIMachineOptions.js
src/UI/reference-ui/src/Images/updateImageInterface.js
src/UI/reference-ui/src/ItkVtkViewer.module.css
src/createViewerMachine.js

Adds a toggle button that enables Cinematic Volume Rendering and shows sliders.
Good tests:
`http://localhost:8082/?image=test-data/ome-ngff-prototypes/single_image/v0.4/zyx.ome.zarr`
and 
`http://localhost:8082/?image=test-data/HeadMRVolume.nrrd`
closes #536

Add Local ambient occlusion

---

src/Rendering/VTKJS/Images/applyCinematicChanged.js
src/Rendering/VTKJS/Images/applyRenderedImage.js
src/Rendering/VTKJS/Images/assignRenderedImage.js
src/Rendering/VTKJS/Main/applyXSlice.js
src/Rendering/VTKJS/Main/applyYSlice.js
src/Rendering/VTKJS/Main/applyZSlice.js
src/Rendering/VTKJS/Main/setBackgroundColor.js
src/Rendering/VTKJS/renderLater.js
src/Rendering/VTKJS/vtkJSRenderingMachineOptions.js
src/Rendering/createRenderingMachine.js
src/UI/reference-ui/src/Images/toggleUseShadow.js
src/createViewer.js
src/createViewerMachine.js
src/index.js
test/createViewerTest.js

Removes RENDER_LATER.  Adds throttling logic to RENDER:
1. `send("RENER")` from somewhere
2. RenderingMachine gets event and calls render
3. RenderingMachine waits for requestAnimationFrame and one tick via setTimeout to try to wait until after paint
4.  Any `send("RENER")` from anywhere, before above timeout fires, transitions from state waitingForRequest to renderRequested.
5. Throttle setTimeout fires and if in renderRequested, call render
closes #576

Throttle render

---

src/IO/fetchBinaryContent.js
src/IO/toMultiscaleSpatialImage.js
src/index.js

In case URL contains options (common for S3 presigned URLs for example),
the code would not be able to extract filename correctly
and 'IO' flow selection would not work.
Fix this by using URL API to robustly parse filename.
Also, change `fetchBinaryContent()` to work with URL objects instead of strings.
URL objects are usually used in the calling code anyway,
so it makes sense to just pass them.

Handle URLs with options and refactor fetchBinaryContent API

---

src/ImJoyPluginAPI.js
src/createViewer.js
test/createViewerTest.js

- Consistent `Image` prefix for image-related parameters
- Shorter, more consistent `Volume` over `Volumetric`

fix(ImJoyAPI): Tweak setVolumeScatteringBlend naming

---

src/IO/MultiscaleSpatialImage.js

This direction matrix was incorrectly transposed
```
-0 0 -1
1 -0 0
0 -1 0
```
This file has the above direction matrix:
http://download.alleninstitute.org/informatics-archive/converted_mouse_ccf/average_template/average_template_50.nii.gz
Related: https://github.com/InsightSoftwareConsortium/itkwidgets/issues/596

fix(MultiscaleSpatialImage): transpose of ITK direction matrix

---

src/Context/ViewerMachineContext.js
src/IO/ZarrMultiscaleSpatialImage.js
src/IO/toMultiscaleSpatialImage.js
test/createViewerTest.js

While we want to constrain the max concurrency when there are many more logical processors on the client than on the server, we should also do the same when there are many more logical processors on the server than the client.

fix(ZarrMultiscaleSpatialImage): Constrain concurrency for large server

---

src/Rendering/VTKJS/Images/fuseImagesUtils.js

For multi-component images, fused data array was too big.

fix(fuseImagesUtils): allocate correct size fused array

---

src/UI/Images/transferFunctionManipulators.js

Cap the step value for the window/level interactor to 10. The `vtkMouseRangeManipulator` appears unresponsive when the step value >= 100.

fix(transferfunctionmanipulators)

---

src/createViewer.js

To address with itkwidgets:
```
caught Error: Unexpected event type: TAKE_SCREENSHOT
at itkVtkViewer.js:161:457719
at itkVtkViewer.js:2:1470699
at Set.forEach (<anonymous>)
at Object.send (itkVtkViewer.js:2:1470671)
at e.sendTo (itkVtkViewer.js:2:1457639)
at e._exec (itkVtkViewer.js:2:1458205)
at e.exec (itkVtkViewer.js:2:1467591)
at e.execute (itkVtkViewer.js:2:1459688)
at e.update (itkVtkViewer.js:2:1460057)
at itkVtkViewer.js:2:1457049
```

fix(createViewer): Handle TAKE_SCREENSHOT event

---

src/IO/InMemoryMultiscaleSpatialImage.js
src/IO/MultiscaleSpatialImage.js

Image would not show up if `direction` matrix was 2D or if a dimension's spatial coordinate array had only 1 element.

Ingestion fixes for 2D images 

---

src/IO/Compare/Compare.cxx
src/IO/Compare/emscripten-build/Compare.js
src/IO/Compare/emscripten-build/Compare.umd.js

Setting ReleaseDataFlagOn() for filters enables checkerboard compare for this dataset:
http://localhost:8082/?rotate=false&image=https://aind-open-data.s3.us-west-2.amazonaws.com/SmartSPIM_000393_2023-01-06_13-35-10_stitched_2023-02-02_22-28-35/processed/OMEZarr/Ex_445_Em_469.zarr&fixedImage=https://aind-open-data.s3.us-west-2.amazonaws.com/SmartSPIM_000393_2023-01-06_13-35-10_stitched_2023-02-02_22-28-35/processed/OMEZarr/Ex_445_Em_469.zarr&compare=checkerboard
Closes #674

Less peak memory for Compare wasm 

---

karma.conf.js
package-lock.json
package.json
src/IO/Analyze/computeHistograms.js
src/IO/Analyze/computeRanges.js
src/IO/Analyze/webWorkerPromiseWorkerPool.js
src/IO/MultiscaleSpatialImage.js
src/Rendering/VTKJS/Images/fuseImages.js
test/createViewerTest.js
webpack.config.js

Stops using webpack worker loader which was configured to build workers as blobs.
Blobs' self.location or `__webpack_public_path__` is not like the document path (index.html).  If the viewer is served off the origin, with a path (ie localhost:8080/some/path/) then the itk-wasm path would not include the path, just the origin.

Fix serving viewer with a path deeper than the origin

---

doc/content/docs/viewer.md
src/Rendering/Images/createImageRenderingActor.js

When adding a component dynamically to an image, the piecewise points
were not clamped to the color range on the second component.

Color range fix

---

src/IO/MultiscaleSpatialImage.js
src/Rendering/VTKJS/Images/updateRenderedImage.js
src/Rendering/VTKJS/Main/croppingPlanes.js
src/internalUtils.js

The image cropping planes were outside the image when the direction vectors of an image "mirror" the spacing.  Example direction vectors: `[-1, -0, -0, -0, -1, -0, 0, 0, -1]`
When a fixed and moving image have different number of scales in MultiscaleImage, there was errors in `updateRenderedImage`

Fixes: negative direction vectors and different number of scales in fixed/moving compare images

---

src/ImJoyPluginAPI.js
src/createViewer.js

Provide the API that we need in order to retrieve information about the data bounds for the current region of interest, as defined by the cropping planes.

Fetch roi info
